services:
  db:
    image: mysql:8.0
    container_name: propro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_local
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password

  wordpress:
    image: wordpress:latest
    container_name: propro_wp
    restart: always
    depends_on:
      - db
    ports:
      - 10090:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db_local
      WORDPRESS_DEBUG: 1
    volumes:
      - ./html:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: propro_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 10099:80
